version: "3"

services:
  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: always
    volumes:
      - .:/app
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: always
    volumes:
      - .:/app